-- ==============================================================================
-- IdeaBridge Supabase Schema (Build with Bharat / Hackathon Edition)
-- ==============================================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES TABLE (Consumers & Startups)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text unique not null,
  role text not null check (role in ('consumer', 'company')),
  name text not null,
  avatar text default '🦊',
  reputation_score integer default 840,
  badges text[] default array['Trend Spotter', 'Early Innovator'],
  company_name text,
  company_category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. IDEAS TABLE
create table if not exists public.ideas (
  id bigint generated by default as identity primary key,
  company text not null,
  cat text not null,
  title text not null,
  description text not null,
  why_reason text,
  author text not null,
  avatar text default '🦊',
  author_id uuid references public.profiles(id) on delete set null,
  score integer default 80 check (score >= 0 and score <= 100),
  buy integer default 70 check (buy >= 0 and buy <= 100),
  opp integer default 80 check (opp >= 0 and opp <= 100),
  status text not null default 'New' check (status in ('New', 'Under Review', 'Testing', 'Shortlisted', 'Prototype', 'Launched', 'Rejected', 'Draft', 'Saved', 'Implemented')),
  comments_count integer default 0,
  price text not null default 'To be validated',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. VOTES TABLE (Community Validation)
create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  idea_id bigint references public.ideas(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (idea_id, user_id)
);

-- 4. COMMENTS TABLE
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  idea_id bigint references public.ideas(id) on delete cascade not null,
  author_name text not null,
  author_avatar text default '🦊',
  author_id uuid references public.profiles(id) on delete set null,
  content text not null,
  is_startup_feedback boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. CHALLENGES TABLE (Startup Briefs)
create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  company text not null,
  cat text not null,
  title text not null,
  description text not null,
  price text not null,
  people text default '500',
  ideas_count text default '50',
  left_time text default '14 days',
  reward text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. PRODUCTS TABLE (Recently Launched / Commercialized)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  company text not null,
  name text not null,
  description text,
  validations_count integer default 3800,
  monthly_revenue text default '₹4.8L',
  consumer_response text default '82% positive',
  status text default 'Launched',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================

alter table public.profiles enable row level security;
alter table public.ideas enable row level security;
alter table public.votes enable row level security;
alter table public.comments enable row level security;
alter table public.challenges enable row level security;
alter table public.products enable row level security;

-- Public can read all ideas, challenges, comments, products, and profiles
create policy "Public ideas viewable by all" on public.ideas for select using (true);
create policy "Public challenges viewable by all" on public.challenges for select using (true);
create policy "Public comments viewable by all" on public.comments for select using (true);
create policy "Public products viewable by all" on public.products for select using (true);
create policy "Public profiles viewable by all" on public.profiles for select using (true);

-- Authenticated users can insert/update ideas
create policy "Users can insert ideas" on public.ideas for insert with check (auth.role() = 'authenticated');
create policy "Users or companies can update ideas" on public.ideas for update using (auth.role() = 'authenticated');

-- Comments & votes
create policy "Authenticated users can vote" on public.votes for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can comment" on public.comments for insert with check (auth.role() = 'authenticated');

-- Challenges inserted by companies
create policy "Companies can insert challenges" on public.challenges for insert with check (auth.role() = 'authenticated');
