import { Startup } from '@/types/startup';
import { Idea } from '@/types/idea';

export const INITIAL_STARTUPS: Startup[] = [
  {
    id: 'startup-nuvie',
    name: 'Nuvie',
    avatar: 'NV',
    category: 'Food & Beverage · Startup',
    stage: 'Early Growth',
    tagline: 'Clean, high-protein functional snacks and low-sugar beverages.',
    description: 'Nuvie is an emerging consumer startup creating high-protein snacks tailored for Indian daily nutrition.',
    productPortfolio: [
      { id: 'p1', name: 'Peanut Butter Crunch Protein Bar', category: 'Food & Beverage', description: 'Real roasted peanuts with peanut butter core and 15g protein.', price: '₹49', isLive: true, tags: ['HighProtein', 'CleanIngredients'] },
      { id: 'p2', name: 'Almond Cocoa Energy Pouch', category: 'Food & Beverage', description: 'Single-serve roasted almond bites sweetened with organic dates.', price: '₹39', isLive: true, tags: ['NoRefinedSugar', 'OnTheGo'] },
      { id: 'p3', name: 'Botanical Cumin Electrolyte Cooler', category: 'Food & Beverage', description: 'Sparkling digestive hydration elixir with spearmint.', price: '₹55', isLive: true, tags: ['ZeroSugar', 'Hydration'] },
    ],
    recentlyLaunched: {
      id: 'rl-nuvie-1',
      name: 'Peanut Butter Crunch Protein Bar',
      category: 'Food & Beverage',
      tagline: 'Launched after 3,842 customer validations and a successful concept test.',
      description: 'Customer-validated medium-sweet protein bar with crunchy roasted peanut coating and 15g natural protein.',
      validationsCount: 3842,
      monthlyRevenue: '₹4.8L',
      consumerResponse: '82% positive',
      netProfit: '₹1.02L',
      margin: '21.3%',
      unitEconomics: {
        productionCost: 21,
        packagingDistribution: 9,
        avgSellingPrice: 49,
        contribution: 19,
      },
      launchResponse: {
        repeatInterest: 68,
        positiveTaste: 82,
        packagingAppeal: 76,
      },
    },
    implementedFinancials: [
      {
        id: 'fin-nuvie-1',
        productName: 'Peanut Butter Crunch Protein Bar',
        originIdeaTitle: 'Peanut Butter Crunch Protein Bar',
        suggestedPrice: '₹49',
        validationsCount: 3842,
        votesCount: 1284,
        monthlyRevenue: '₹4.8L',
        unitsPerMonth: '9,800 units / month',
        annualOpportunity: '₹57.6L',
        productionCostMonthly: '₹2.05L / mo',
        operatingCostMonthly: '₹88K / mo',
        netProfitMonthly: '₹1.02L / mo',
        marginPercentage: '21.3%',
        growthPotentialYoY: '+24% YoY',
        breakdown: {
          production: 205,
          operating: 88,
          netProfit: 102,
        },
      },
    ],
    scoutingMandate: {
      whatWeAreLookingFor: [
        'Low-sugar functional snacks',
        'Clean-label protein formulation (12g–18g)',
        'Portable 35g–50g single-serve packaging',
        'Indian flavor alignment (Peanut, Cocoa, Cardamom)',
        'Affordable accessible price points (₹40–₹60)',
      ],
      rewardsAndPerks: [
        'Founder tasting feedback session',
        'Nuvie 3-month product hamper',
        'Early access to commercial batch launch',
        'Co-creator recognition on Nuvie packaging',
        '₹15,000 innovation cash grant',
      ],
      targetAudience: 'College students & young working professionals aged 18–30',
      priceRange: '₹40–₹60',
      validationThreshold: '>75% purchase intent & >500 community validations',
      pipelineFocus: 'High-protein snack bars & electrolyte coolers',
    },
    emergingTrends: [
      {
        id: 'trend-nv-1',
        trendNumber: 1,
        title: 'Low-Sugar Protein Snacking',
        confidence: 91,
        responsesCount: 3840,
        bullets: [
          'Strong demand among 18–30 age group',
          'Customers want sweetness without artificial sweeteners',
          '₹40–₹50 appears to be the strongest price range',
        ],
      },
      {
        id: 'trend-nv-2',
        trendNumber: 2,
        title: 'Smaller Portable Packaging',
        confidence: 84,
        responsesCount: 3210,
        bullets: [
          '35g format requested repeatedly across customer comments',
          'Framed around reducing mess and pocket portability',
          'Popular with daily office commuters and gym-goers',
        ],
      },
      {
        id: 'trend-nv-3',
        trendNumber: 3,
        title: 'Roasted Indian Peanut Blends',
        confidence: 79,
        responsesCount: 2440,
        bullets: [
          'High craving for real roasted peanut crunch texture',
          'Viewed as natural and nutritious alternative to imported bars',
          'Sub-₹50 perceived as exceptional value for money',
        ],
      },
      {
        id: 'trend-nv-4',
        trendNumber: 4,
        title: 'Clean Ingredient Claims',
        confidence: 76,
        responsesCount: 1980,
        bullets: [
          'Zero palm oil and zero refined sugar validation',
          'Simple front-of-pack ingredient clarity demanded',
          'High driver of repeat subscriptions and trust',
        ],
      },
    ],
    aiInsightQuote:
      'Customers increasingly want affordable protein snacks under ₹50 with clean, recognizable ingredients. The strongest opportunity appears to be a ₹45–₹50 crunchy bar targeted at consumers aged 18–30.',
    analytics: {
      weeklyDemand: [
        { week: 'Week 1', validations: 420, heightPct: '35%' },
        { week: 'Week 2', validations: 510, heightPct: '42%' },
        { week: 'Week 3', validations: 640, heightPct: '53%' },
        { week: 'Week 4', validations: 780, heightPct: '65%' },
        { week: 'Week 5', validations: 930, heightPct: '78%' },
        { week: 'Week 6', validations: 1180, heightPct: '95%' },
      ],
      demographics: [
        { group: '18–24 years', pct: 42, count: 420, color: '#4f46e5' },
        { group: '25–30 years', pct: 31, count: 310, color: '#f59e0b' },
        { group: '31–40 years', pct: 18, count: 180, color: '#0d9488' },
        { group: '41+ years', pct: 9, count: 90, color: '#6366f1' },
      ],
      priceSensitivity: [
        { price: '₹30', acceptancePct: 78 },
        { price: '₹40', acceptancePct: 70 },
        { price: '₹50', acceptancePct: 58 },
        { price: '₹60', acceptancePct: 41 },
        { price: '₹70+', acceptancePct: 24 },
      ],
      productAreaDemand: [
        { area: 'Protein Bars', count: 184, pct: 100 },
        { area: 'Protein Shakes', count: 126, pct: 68 },
        { area: 'Snack Packs', count: 82, pct: 45 },
        { area: 'Packaging Formats', count: 61, pct: 33 },
      ],
    },
  },
  {
    id: 'startup-godesi',
    name: 'Go Desi',
    avatar: 'GD',
    category: 'Food & Beverage · Regional Treats',
    stage: 'Growth Stage',
    tagline: 'Authentic Indian regional confectionery and nostalgic fruit coolers.',
    description: 'Go Desi manufactures traditional regional Indian snacks, fruit pops, and coolers using farm-fresh ingredients.',
    productPortfolio: [
      { id: 'gd-1', name: 'Desi Popz Real Tangy Imli', category: 'Food & Beverage', description: 'Traditional spicy-sweet tamarind pop.', price: '₹15', isLive: true, tags: ['Nostalgic', 'Traditional'] },
      { id: 'gd-2', name: 'Kaccha Aam Spicy Chunks', category: 'Food & Beverage', description: 'Sun-dried raw mango with black salt.', price: '₹25', isLive: true, tags: ['RawMango', 'Snack'] },
    ],
    recentlyLaunched: {
      id: 'rl-godesi-1',
      name: 'Aam Panna Sparkling Cooler',
      category: 'Food & Beverage',
      tagline: 'Validated by 2,140 regional beverage lovers.',
      description: 'Nostalgic raw mango cooler with black salt and roasted jeera.',
      validationsCount: 2140,
      monthlyRevenue: '₹3.6L',
      consumerResponse: '78% positive',
      netProfit: '₹88k',
      margin: '24.4%',
      unitEconomics: { productionCost: 16, packagingDistribution: 7, avgSellingPrice: 39, contribution: 16 },
      launchResponse: { repeatInterest: 62, positiveTaste: 84, packagingAppeal: 73 },
    },
    implementedFinancials: [
      {
        id: 'fin-godesi-1',
        productName: 'Aam Panna Sparkling Cooler',
        originIdeaTitle: 'Aam Panna Sparkling Cooler',
        suggestedPrice: '₹39',
        validationsCount: 2140,
        votesCount: 840,
        monthlyRevenue: '₹3.6L',
        unitsPerMonth: '9,200 units / month',
        annualOpportunity: '₹43.2L',
        productionCostMonthly: '₹1.48L / mo',
        operatingCostMonthly: '₹64K / mo',
        netProfitMonthly: '₹88K / mo',
        marginPercentage: '24.4%',
        growthPotentialYoY: '+29% YoY',
        breakdown: {
          production: 148,
          operating: 64,
          netProfit: 88,
        },
      },
    ],
    scoutingMandate: {
      whatWeAreLookingFor: [
        'Traditional Indian regional fruit and spice profiles',
        'Mess-free pocket candies & tangy fruit pops',
        'Farm-fresh ingredients & jaggery sweeteners',
        'Compostable or recyclable packaging',
        'Budget-accessible single-serve pricing (₹15–₹40)',
      ],
      rewardsAndPerks: [
        'Go Desi regional treats gift box',
        'Co-creator credit on brand campaign',
        'Exclusive tasting kit of test formulas',
        '₹10,000 Go Desi shopping voucher',
      ],
      targetAudience: 'Tier 1 & Tier 2 families, college students, nostalgic snackers',
      priceRange: '₹15–₹40',
      validationThreshold: '>70% purchase intent & >400 community validations',
      pipelineFocus: 'Sparkling coolers and sun-dried fruit confectionery',
    },
    emergingTrends: [
      {
        id: 'trend-gd-1',
        trendNumber: 1,
        title: 'Spiced Indian Coolers',
        confidence: 89,
        responsesCount: 2750,
        bullets: [
          'Desire for authentic raw mango & roasted cumin cooling notes',
          'Dislike of artificial soda syrups and preservatives',
          '₹30–₹40 ready-to-drink cans strongly favored',
        ],
      },
      {
        id: 'trend-gd-2',
        trendNumber: 2,
        title: 'Pocket Confectionery Formats',
        confidence: 82,
        responsesCount: 2110,
        bullets: [
          'Single-serve stick format for hygienic travel snacking',
          'Popular for desk snacking and university breaks',
          'High impulse buying potential at checkout counters',
        ],
      },
      {
        id: 'trend-gd-3',
        trendNumber: 3,
        title: 'Natural Jaggery Sweeteners',
        confidence: 77,
        responsesCount: 1830,
        bullets: [
          'Growing rejection of refined sugar in traditional sweets',
          'Farm-direct jaggery perceived as immunity-boosting',
          'Strong parent approval for children snacking',
        ],
      },
      {
        id: 'trend-gd-4',
        trendNumber: 4,
        title: 'Eco-Craft Packaging',
        confidence: 73,
        responsesCount: 1460,
        bullets: [
          'Paper-wrapped pops and zero-plastic wrappers requested',
          'Compostable bamboo sticks appreciated by urban youth',
          'Clear organic certification labels build high trust',
        ],
      },
    ],
    aiInsightQuote:
      'Consumers want authentic nostalgic regional flavors without artificial chemicals. Spiced raw mango and tamarind coolers with sparkling carbonation are currently the highest-converting opportunity.',
    analytics: {
      weeklyDemand: [
        { week: 'Week 1', validations: 310, heightPct: '30%' },
        { week: 'Week 2', validations: 440, heightPct: '42%' },
        { week: 'Week 3', validations: 580, heightPct: '55%' },
        { week: 'Week 4', validations: 710, heightPct: '68%' },
        { week: 'Week 5', validations: 850, heightPct: '81%' },
        { week: 'Week 6', validations: 1040, heightPct: '94%' },
      ],
      demographics: [
        { group: '18–24 years', pct: 36, count: 360, color: '#4f46e5' },
        { group: '25–30 years', pct: 34, count: 340, color: '#f59e0b' },
        { group: '31–40 years', pct: 20, count: 200, color: '#0d9488' },
        { group: '41+ years', pct: 10, count: 100, color: '#6366f1' },
      ],
      priceSensitivity: [
        { price: '₹20', acceptancePct: 88 },
        { price: '₹30', acceptancePct: 79 },
        { price: '₹40', acceptancePct: 65 },
        { price: '₹50', acceptancePct: 38 },
        { price: '₹60+', acceptancePct: 18 },
      ],
      productAreaDemand: [
        { area: 'Fruit Coolers', count: 156, pct: 100 },
        { area: 'Tangy Pops', count: 118, pct: 76 },
        { area: 'Dried Fruit Bites', count: 74, pct: 47 },
        { area: 'Regional Spices', count: 48, pct: 31 },
      ],
    },
  },
  {
    id: 'startup-solestory',
    name: 'SoleStory',
    avatar: 'SS',
    category: 'Sneakers · Footwear',
    stage: 'Seed Stage',
    tagline: 'High-comfort college sneakers with premium packaging at sub-₹1,600 pricing.',
    description: 'SoleStory engineers stylish, breathable footwear for Indian college students and young commuters.',
    productPortfolio: [
      { id: 'ss-1', name: 'Daily Classic Canvas Low', category: 'Sneakers', description: 'Vulcanized sole with memory foam insole.', price: '₹1,499', isLive: true, tags: ['College', 'MemoryFoam'] },
    ],
    recentlyLaunched: {
      id: 'rl-solestory-1',
      name: 'Eco-Craft Unboxing Pack',
      category: 'Sneakers',
      tagline: 'Co-created with 1,890 sneakerheads.',
      description: 'Zero-glue recycled shoe box with custom dust bag and sneaker guide.',
      validationsCount: 1890,
      monthlyRevenue: '₹5.2L',
      consumerResponse: '86% positive',
      netProfit: '₹1.15L',
      margin: '22.1%',
      unitEconomics: { productionCost: 45, packagingDistribution: 20, avgSellingPrice: 110, contribution: 45 },
      launchResponse: { repeatInterest: 71, positiveTaste: 88, packagingAppeal: 92 },
    },
    implementedFinancials: [
      {
        id: 'fin-solestory-1',
        productName: 'Eco-Craft Unboxing Pack',
        originIdeaTitle: 'Eco-Craft Unboxing Pack',
        suggestedPrice: '₹1,499',
        validationsCount: 1890,
        votesCount: 710,
        monthlyRevenue: '₹5.2L',
        unitsPerMonth: '350 pairs / month',
        annualOpportunity: '₹62.4L',
        productionCostMonthly: '₹2.85L / mo',
        operatingCostMonthly: '₹1.20L / mo',
        netProfitMonthly: '₹1.15L / mo',
        marginPercentage: '22.1%',
        growthPotentialYoY: '+34% YoY',
        breakdown: {
          production: 285,
          operating: 120,
          netProfit: 115,
        },
      },
    ],
    scoutingMandate: {
      whatWeAreLookingFor: [
        'Anti-crease flexible toe-box materials',
        'Breathable mesh suitable for humid Indian colleges',
        'Recyclable mono-material shoebox packaging',
        'College lifestyle aesthetic under ₹1,600',
      ],
      rewardsAndPerks: [
        'Free pair of SoleStory sneakers',
        'Co-designer badge and mention in launch lookbook',
        'Access to prototype test fittings',
        '₹12,000 sneaker voucher',
      ],
      targetAudience: 'College students and young metro commuters aged 17–26',
      priceRange: '₹1,200–₹1,800',
      validationThreshold: '>80% purchase intent & >350 validations',
      pipelineFocus: 'Lightweight canvas sneakers & recyclable packaging',
    },
    emergingTrends: [
      {
        id: 'trend-ss-1',
        trendNumber: 1,
        title: 'Anti-Crease Footwear Formats',
        confidence: 93,
        responsesCount: 2980,
        bullets: [
          'College students prioritize sneaker aesthetics staying crisp',
          'Willingness to buy if toe-box resists walking creases',
          'Sub-₹1,600 price point considered sweet spot',
        ],
      },
      {
        id: 'trend-ss-2',
        trendNumber: 2,
        title: 'Sustainable Unboxing Experience',
        confidence: 86,
        responsesCount: 2190,
        bullets: [
          'Demand for zero-glue recycled cardboard packaging',
          'Reusable fabric dust bag preferred over disposable plastics',
          'Unboxing video virality potential on Instagram',
        ],
      },
      {
        id: 'trend-ss-3',
        trendNumber: 3,
        title: 'Memory Foam Everyday Insoles',
        confidence: 80,
        responsesCount: 1740,
        bullets: [
          'High importance placed on all-day campus walking comfort',
          'Arch support needed for public transit commuting',
          'Direct driver of 5-star customer reviews',
        ],
      },
      {
        id: 'trend-ss-4',
        trendNumber: 4,
        title: 'Neutral Minimalist Colorways',
        confidence: 75,
        responsesCount: 1320,
        bullets: [
          'Off-white, slate grey, and olive green preferred',
          'Easy pairing with denim and casual college wear',
          'Lower return rate on understated color palettes',
        ],
      },
    ],
    aiInsightQuote:
      'College students demand premium streetwear aesthetics and walking comfort at sub-₹1,600 pricing. Eco-craft unboxing and anti-crease durability generate the strongest purchase desire.',
    analytics: {
      weeklyDemand: [
        { week: 'Week 1', validations: 240, heightPct: '26%' },
        { week: 'Week 2', validations: 380, heightPct: '40%' },
        { week: 'Week 3', validations: 520, heightPct: '54%' },
        { week: 'Week 4', validations: 670, heightPct: '68%' },
        { week: 'Week 5', validations: 810, heightPct: '82%' },
        { week: 'Week 6', validations: 980, heightPct: '94%' },
      ],
      demographics: [
        { group: '18–24 years', pct: 64, count: 640, color: '#4f46e5' },
        { group: '25–30 years', pct: 24, count: 240, color: '#f59e0b' },
        { group: '31–40 years', pct: 8, count: 80, color: '#0d9488' },
        { group: '41+ years', pct: 4, count: 40, color: '#6366f1' },
      ],
      priceSensitivity: [
        { price: '₹1,200', acceptancePct: 86 },
        { price: '₹1,400', acceptancePct: 74 },
        { price: '₹1,600', acceptancePct: 56 },
        { price: '₹1,800', acceptancePct: 34 },
        { price: '₹2,000+', acceptancePct: 16 },
      ],
      productAreaDemand: [
        { area: 'Campus Lows', count: 142, pct: 100 },
        { area: 'High-Tops', count: 96, pct: 67 },
        { area: 'Slip-Ons', count: 68, pct: 48 },
        { area: 'Packaging & Dust Bags', count: 54, pct: 38 },
      ],
    },
  },
  {
    id: 'startup-threadtheory',
    name: 'ThreadTheory',
    avatar: 'TT',
    category: 'Clothing · Everyday Essentials',
    stage: 'Seed Stage',
    tagline: 'Thoughtful weather-ready apparel designed for humid Indian climates.',
    description: 'ThreadTheory builds breathable, pocket-first apparel engineered for everyday Indian life.',
    productPortfolio: [
      { id: 'tt-1', name: 'Breeze Cotton Daily Tee', category: 'Clothing', description: 'Pre-shrunk supima cotton with anti-odor weave.', price: '₹599', isLive: true, tags: ['100%Cotton', 'Breathable'] },
    ],
    recentlyLaunched: {
      id: 'rl-tt-1',
      name: 'Monsoon Quick-Dry Overshirt',
      category: 'Clothing',
      tagline: 'Co-designed with 1,420 city commuters.',
      description: 'Featherlight water-repellent overshirt with hidden passport pocket.',
      validationsCount: 1420,
      monthlyRevenue: '₹4.1L',
      consumerResponse: '80% positive',
      netProfit: '₹94k',
      margin: '22.9%',
      unitEconomics: { productionCost: 320, packagingDistribution: 60, avgSellingPrice: 899, contribution: 519 },
      launchResponse: { repeatInterest: 66, positiveTaste: 79, packagingAppeal: 84 },
    },
    implementedFinancials: [
      {
        id: 'fin-tt-1',
        productName: 'Monsoon Quick-Dry Overshirt',
        originIdeaTitle: 'Monsoon Quick-Dry Overshirt',
        suggestedPrice: '₹899',
        validationsCount: 1420,
        votesCount: 560,
        monthlyRevenue: '₹4.1L',
        unitsPerMonth: '460 units / month',
        annualOpportunity: '₹49.2L',
        productionCostMonthly: '₹2.10L / mo',
        operatingCostMonthly: '₹1.06L / mo',
        netProfitMonthly: '₹94K / mo',
        marginPercentage: '22.9%',
        growthPotentialYoY: '+26% YoY',
        breakdown: {
          production: 210,
          operating: 106,
          netProfit: 94,
        },
      },
    ],
    scoutingMandate: {
      whatWeAreLookingFor: [
        'Weather-adaptive and quick-dry natural fabrics',
        'Functional hidden pockets for transit cards and phones',
        'Pre-shrunk organic cotton blends for Indian monsoons',
        'Smart everyday silhouettes under ₹999',
      ],
      rewardsAndPerks: [
        'Full ThreadTheory wardrobe capsule',
        'Named acknowledgment in garment tags',
        'Fabric lab visit and early sampling',
        '₹10,000 apparel voucher',
      ],
      targetAudience: 'Young working professionals and metro commuters aged 21–35',
      priceRange: '₹599–₹999',
      validationThreshold: '>75% purchase intent & >300 validations',
      pipelineFocus: 'Lightweight linen overshirts and commuter chinos',
    },
    emergingTrends: [
      {
        id: 'trend-tt-1',
        trendNumber: 1,
        title: 'Quick-Dry Monsoon Weaves',
        confidence: 88,
        responsesCount: 2310,
        bullets: [
          'Commuters need shirts that dry fast after sudden rain showers',
          'Must maintain natural cotton touch without plastic sheen',
          'High demand during June–September across metro corridors',
        ],
      },
      {
        id: 'trend-tt-2',
        trendNumber: 2,
        title: 'Hidden Security Pockets',
        confidence: 82,
        responsesCount: 1890,
        bullets: [
          'Concealed zippered pockets for metro cards and phones',
          'Reduces theft anxiety during crowded bus/train commutes',
          'Strong differentiator against standard retail shirts',
        ],
      },
      {
        id: 'trend-tt-3',
        trendNumber: 3,
        title: 'Anti-Odor Natural Fibers',
        confidence: 76,
        responsesCount: 1540,
        bullets: [
          'Silver-ion or neem antimicrobial finishing preferred',
          'Eliminates sweat odor during hot afternoon travel',
          'Supports all-day wear from desk to evening dinner',
        ],
      },
      {
        id: 'trend-tt-4',
        trendNumber: 4,
        title: 'Wrinkle-Resistant Packaging',
        confidence: 71,
        responsesCount: 1180,
        bullets: [
          'Roll-pack delivery envelopes reducing retail creases',
          'Ready-to-wear straight out of courier packaging',
          'Lower return rates due to initial unboxing fit',
        ],
      },
    ],
    aiInsightQuote:
      'Indian city commuters strongly favor functional, quick-drying natural fabrics with discreet utility pockets that transition smoothly from work to evening commutes.',
    analytics: {
      weeklyDemand: [
        { week: 'Week 1', validations: 210, heightPct: '28%' },
        { week: 'Week 2', validations: 320, heightPct: '41%' },
        { week: 'Week 3', validations: 460, heightPct: '57%' },
        { week: 'Week 4', validations: 590, heightPct: '71%' },
        { week: 'Week 5', validations: 720, heightPct: '84%' },
        { week: 'Week 6', validations: 880, heightPct: '95%' },
      ],
      demographics: [
        { group: '18–24 years', pct: 32, count: 320, color: '#4f46e5' },
        { group: '25–30 years', pct: 45, count: 450, color: '#f59e0b' },
        { group: '31–40 years', pct: 18, count: 180, color: '#0d9488' },
        { group: '41+ years', pct: 5, count: 50, color: '#6366f1' },
      ],
      priceSensitivity: [
        { price: '₹499', acceptancePct: 82 },
        { price: '₹699', acceptancePct: 71 },
        { price: '₹899', acceptancePct: 54 },
        { price: '₹1,099', acceptancePct: 32 },
        { price: '₹1,299+', acceptancePct: 15 },
      ],
      productAreaDemand: [
        { area: 'Commuter Overshirts', count: 128, pct: 100 },
        { area: 'Daily Supima Tees', count: 98, pct: 76 },
        { area: 'Breathable Chinos', count: 64, pct: 50 },
        { area: 'Weather-Proof Layers', count: 42, pct: 33 },
      ],
    },
  },
  {
    id: 'startup-auranest',
    name: 'AuraNest',
    avatar: 'AN',
    category: 'Fragrances · Wellness',
    stage: 'Seed Stage',
    tagline: 'Pocket-friendly artisan roll-on perfumes inspired by Indian spices and woods.',
    description: 'AuraNest makes alcohol-free attar and roll-on fragrances made with authentic essential oils.',
    productPortfolio: [],
    recentlyLaunched: {
      id: 'rl-an-1',
      name: 'Chai & Cedar Roll-on',
      category: 'Fragrances',
      tagline: 'Tested with 940 fragrance enthusiasts.',
      description: 'Warm spiced cardamom top notes with cedarwood dry-down.',
      validationsCount: 940,
      monthlyRevenue: '₹2.8L',
      consumerResponse: '85% positive',
      netProfit: '₹75k',
      margin: '26.8%',
      unitEconomics: { productionCost: 75, packagingDistribution: 25, avgSellingPrice: 279, contribution: 179 },
      launchResponse: { repeatInterest: 74, positiveTaste: 87, packagingAppeal: 81 },
    },
    implementedFinancials: [
      {
        id: 'fin-an-1',
        productName: 'Chai & Cedar Roll-on',
        originIdeaTitle: 'Chai & Cedar Roll-on',
        suggestedPrice: '₹279',
        validationsCount: 940,
        votesCount: 420,
        monthlyRevenue: '₹2.8L',
        unitsPerMonth: '1,000 units / month',
        annualOpportunity: '₹33.6L',
        productionCostMonthly: '₹1.15L / mo',
        operatingCostMonthly: '₹90K / mo',
        netProfitMonthly: '₹75K / mo',
        marginPercentage: '26.8%',
        growthPotentialYoY: '+38% YoY',
        breakdown: {
          production: 115,
          operating: 90,
          netProfit: 75,
        },
      },
    ],
    scoutingMandate: {
      whatWeAreLookingFor: [
        'Alcohol-free natural attars and long-lasting oil roll-ons',
        'Warm Indian spice accords (Cardamom, Vetiver, Sandalwood)',
        'Compact 10ml leak-proof pocket glass bottles',
        'Gender-neutral scent profiles under ₹299',
      ],
      rewardsAndPerks: [
        'Custom perfume discovery box',
        'Name inscribed on the fragrance packaging',
        'Fragrance formulation workshop pass',
        '₹8,000 AuraNest shopping voucher',
      ],
      targetAudience: 'College students and young professionals seeking distinctive scents',
      priceRange: '₹199–₹349',
      validationThreshold: '>80% purchase intent & >250 validations',
      pipelineFocus: 'Oil-based perfume roll-ons & scented soy candles',
    },
    emergingTrends: [
      {
        id: 'trend-an-1',
        trendNumber: 1,
        title: 'Spiced Cardamom & Chai Accords',
        confidence: 90,
        responsesCount: 1980,
        bullets: [
          'High emotional resonance with comforting Indian spices',
          'Preference for subtle gourmand notes over sharp synthetic perfumes',
          'Sub-₹299 roll-on price triggers strong impulse gifting',
        ],
      },
      {
        id: 'trend-an-2',
        trendNumber: 2,
        title: 'Alcohol-Free Long Lasting Oils',
        confidence: 84,
        responsesCount: 1620,
        bullets: [
          'Skin-friendly pure botanical jojoba oil base',
          'Scent projection lasts 8+ hours without fading',
          'Suitable for sensitive skin and religious occasions',
        ],
      },
      {
        id: 'trend-an-3',
        trendNumber: 3,
        title: 'Pocket Leak-Proof Rollerballs',
        confidence: 78,
        responsesCount: 1350,
        bullets: [
          'Sturdy amber glass with leak-tested metal rollerball',
          'Fits easily in college jeans pocket or handbag',
          'Easy reapplication during midday transit',
        ],
      },
      {
        id: 'trend-an-4',
        trendNumber: 4,
        title: 'Gender-Neutral Woody Blends',
        confidence: 72,
        responsesCount: 1040,
        bullets: [
          'Sandalwood, vetiver (khus), and cedarwood combinations',
          'Equally purchased by men and women',
          'Minimalist aesthetic packaging preferred',
        ],
      },
    ],
    aiInsightQuote:
      'Consumers are moving away from expensive synthetic sprays toward intimate, long-lasting botanical roll-on oils celebrating Indian spices and woods under ₹299.',
    analytics: {
      weeklyDemand: [
        { week: 'Week 1', validations: 160, heightPct: '25%' },
        { week: 'Week 2', validations: 270, heightPct: '41%' },
        { week: 'Week 3', validations: 390, heightPct: '58%' },
        { week: 'Week 4', validations: 510, heightPct: '72%' },
        { week: 'Week 5', validations: 630, heightPct: '84%' },
        { week: 'Week 6', validations: 790, heightPct: '96%' },
      ],
      demographics: [
        { group: '18–24 years', pct: 48, count: 480, color: '#4f46e5' },
        { group: '25–30 years', pct: 36, count: 360, color: '#f59e0b' },
        { group: '31–40 years', pct: 12, count: 120, color: '#0d9488' },
        { group: '41+ years', pct: 4, count: 40, color: '#6366f1' },
      ],
      priceSensitivity: [
        { price: '₹199', acceptancePct: 89 },
        { price: '₹249', acceptancePct: 78 },
        { price: '₹299', acceptancePct: 62 },
        { price: '₹349', acceptancePct: 40 },
        { price: '₹399+', acceptancePct: 19 },
      ],
      productAreaDemand: [
        { area: 'Spiced Roll-Ons', count: 112, pct: 100 },
        { area: 'Woody Attars', count: 86, pct: 77 },
        { area: 'Floral Solid Perfumes', count: 54, pct: 48 },
        { area: 'Gift Sets', count: 38, pct: 34 },
      ],
    },
  },
  {
    id: 'startup-giftly',
    name: 'Giftly',
    avatar: 'GF',
    category: 'Gifting · D2C',
    stage: 'Bootstrapped',
    tagline: 'Build-your-own personalized mini gift hampers under ₹500.',
    description: 'Giftly curates affordable, high-delight gift sets for college birthdays and festivities.',
    productPortfolio: [],
    recentlyLaunched: {
      id: 'rl-gf-1',
      name: 'Personalized 3-Item Mini Hamper',
      category: 'Gifting',
      tagline: 'Co-created with 820 college shoppers.',
      description: 'Choice of artisan candle, mini snack jar, and seeded paper message card.',
      validationsCount: 820,
      monthlyRevenue: '₹3.1L',
      consumerResponse: '83% positive',
      netProfit: '₹68k',
      margin: '21.9%',
      unitEconomics: { productionCost: 180, packagingDistribution: 40, avgSellingPrice: 449, contribution: 229 },
      launchResponse: { repeatInterest: 64, positiveTaste: 82, packagingAppeal: 89 },
    },
    implementedFinancials: [
      {
        id: 'fin-gf-1',
        productName: 'Personalized 3-Item Mini Hamper',
        originIdeaTitle: 'Personalized 3-Item Mini Hamper',
        suggestedPrice: '₹449',
        validationsCount: 820,
        votesCount: 390,
        monthlyRevenue: '₹3.1L',
        unitsPerMonth: '690 hampers / month',
        annualOpportunity: '₹37.2L',
        productionCostMonthly: '₹1.52L / mo',
        operatingCostMonthly: '₹90K / mo',
        netProfitMonthly: '₹68K / mo',
        marginPercentage: '21.9%',
        growthPotentialYoY: '+31% YoY',
        breakdown: {
          production: 152,
          operating: 90,
          netProfit: 68,
        },
      },
    ],
    scoutingMandate: {
      whatWeAreLookingFor: [
        'Modular mini gift items suitable for personalized mixing',
        'Zero-waste seeded paper cards and recycled craft boxes',
        'College milestone and friendship celebration themes',
        'Sub-₹499 pricing with premium unboxing touch',
      ],
      rewardsAndPerks: [
        'Curated holiday gift hamper',
        'Co-curator credit on Giftly digital catalogue',
        'Exclusive early testing of seasonal gift bundles',
        '₹8,000 gifting credits',
      ],
      targetAudience: 'College students, Gen Z friends, and young corporate peers',
      priceRange: '₹349–₹499',
      validationThreshold: '>75% purchase intent & >200 validations',
      pipelineFocus: 'Modular 3-item keepsake boxes & seeded plantable cards',
    },
    emergingTrends: [
      {
        id: 'trend-gf-1',
        trendNumber: 1,
        title: 'Sub-₹500 Curated Hampers',
        confidence: 88,
        responsesCount: 1740,
        bullets: [
          'Strong demand for budget-friendly birthday gift options',
          'Eliminates the guilt of buying expensive commercial hampers',
          'High purchase intent for multi-friend group contributions',
        ],
      },
      {
        id: 'trend-gf-2',
        trendNumber: 2,
        title: 'Seeded Plantable Greeting Cards',
        confidence: 83,
        responsesCount: 1420,
        bullets: [
          'Handmade paper embedded with marigold and basil seeds',
          'Emotional keepsakes that grow into plants rather than trash',
          'Differentiates Giftly unboxing from generic printed cards',
        ],
      },
      {
        id: 'trend-gf-3',
        trendNumber: 3,
        title: 'Artisan Micro-Candles & Jars',
        confidence: 76,
        responsesCount: 1190,
        bullets: [
          'Compact soy wax votives with nostalgic scents',
          'Handmade dry-fruit honey mini jars',
          'Premium tactile feeling in a small box format',
        ],
      },
      {
        id: 'trend-gf-4',
        trendNumber: 4,
        title: 'Handwritten Calligraphy Notes',
        confidence: 70,
        responsesCount: 890,
        bullets: [
          'Option to print genuine handwritten style notes',
          'Personalized emotional touch for long-distance friends',
          'Zero extra packaging clutter',
        ],
      },
    ],
    aiInsightQuote:
      'College students and young friends want thoughtful, personalized mini gift sets under ₹500 that feel handcrafted and meaningful without high corporate price tags.',
    analytics: {
      weeklyDemand: [
        { week: 'Week 1', validations: 140, heightPct: '24%' },
        { week: 'Week 2', validations: 230, heightPct: '38%' },
        { week: 'Week 3', validations: 340, heightPct: '54%' },
        { week: 'Week 4', validations: 470, heightPct: '71%' },
        { week: 'Week 5', validations: 590, heightPct: '85%' },
        { week: 'Week 6', validations: 710, heightPct: '95%' },
      ],
      demographics: [
        { group: '18–24 years', pct: 58, count: 580, color: '#4f46e5' },
        { group: '25–30 years', pct: 28, count: 280, color: '#f59e0b' },
        { group: '31–40 years', pct: 10, count: 100, color: '#0d9488' },
        { group: '41+ years', pct: 4, count: 40, color: '#6366f1' },
      ],
      priceSensitivity: [
        { price: '₹299', acceptancePct: 86 },
        { price: '₹399', acceptancePct: 74 },
        { price: '₹449', acceptancePct: 61 },
        { price: '₹499', acceptancePct: 44 },
        { price: '₹599+', acceptancePct: 20 },
      ],
      productAreaDemand: [
        { area: 'Mini Birthday Boxes', count: 98, pct: 100 },
        { area: 'Seeded Message Cards', count: 76, pct: 78 },
        { area: 'Artisan Scent Jars', count: 52, pct: 53 },
        { area: 'Festive Bundles', count: 36, pct: 37 },
      ],
    },
  },
  {
    id: 'startup-urbancarry',
    name: 'UrbanCarry',
    avatar: 'UC',
    category: 'Accessories · Travel',
    stage: 'Seed Stage',
    tagline: 'Slim, pocket-dense commuter laptop totes and bags.',
    description: 'UrbanCarry engineers durable vegan-leather and canvas totes for university students.',
    productPortfolio: [],
    recentlyLaunched: {
      id: 'rl-uc-1',
      name: 'Slim Everyday Commute Tote',
      category: 'Accessories',
      tagline: 'Co-created with 1,120 daily metro commuters.',
      description: 'Hidden insulated bottle pocket, padded 14-inch laptop sleeve, waterproof base.',
      validationsCount: 1120,
      monthlyRevenue: '₹4.4L',
      consumerResponse: '81% positive',
      netProfit: '₹1.05L',
      margin: '23.8%',
      unitEconomics: { productionCost: 390, packagingDistribution: 65, avgSellingPrice: 999, contribution: 544 },
      launchResponse: { repeatInterest: 67, positiveTaste: 81, packagingAppeal: 86 },
    },
    implementedFinancials: [
      {
        id: 'fin-uc-1',
        productName: 'Slim Everyday Commute Tote',
        originIdeaTitle: 'Slim Everyday Commute Tote',
        suggestedPrice: '₹999',
        validationsCount: 1120,
        votesCount: 480,
        monthlyRevenue: '₹4.4L',
        unitsPerMonth: '440 bags / month',
        annualOpportunity: '₹52.8L',
        productionCostMonthly: '₹2.15L / mo',
        operatingCostMonthly: '₹1.20L / mo',
        netProfitMonthly: '₹1.05L / mo',
        marginPercentage: '23.8%',
        growthPotentialYoY: '+28% YoY',
        breakdown: {
          production: 215,
          operating: 120,
          netProfit: 105,
        },
      },
    ],
    scoutingMandate: {
      whatWeAreLookingFor: [
        'Ergonomic shoulder straps engineered for heavy laptops',
        'Water-resistant canvas and vegan leather accents',
        'Integrated umbrella & insulated water bottle sleeves',
        'Minimalist metropolitan aesthetics under ₹1,200',
      ],
      rewardsAndPerks: [
        'Free custom UrbanCarry laptop bag',
        'Design credit in product hangtag',
        'Access to hardware and fabric testing reviews',
        '₹12,000 product voucher',
      ],
      targetAudience: 'Metro commuters, university students, remote workers aged 20–35',
      priceRange: '₹899–₹1,299',
      validationThreshold: '>75% purchase intent & >300 validations',
      pipelineFocus: 'Slim commuter totes & anti-theft sling bags',
    },
    emergingTrends: [
      {
        id: 'trend-uc-1',
        trendNumber: 1,
        title: 'Hidden Insulated Bottle Pockets',
        confidence: 91,
        responsesCount: 2150,
        bullets: [
          'High frustration with water bottles leaking onto laptops inside bags',
          'Dedicated insulated thermal sleeve is a major decision driver',
          'Maintains water temperature during 90-minute metro travel',
        ],
      },
      {
        id: 'trend-uc-2',
        trendNumber: 2,
        title: 'Anti-Theft Quick Access Zippers',
        confidence: 84,
        responsesCount: 1780,
        bullets: [
          'Concealed back-panel zipper for wallet and transit cards',
          'Reduces pickpocketing fears in crowded stations',
          'Subtle clean design without bulky external padlocks',
        ],
      },
      {
        id: 'trend-uc-3',
        trendNumber: 3,
        title: 'Waterproof Reinforced Base',
        confidence: 79,
        responsesCount: 1460,
        bullets: [
          'Durability when placing bag on metro floors or cafe benches',
          'Easy wipe-clean rubberized base material',
          'Addresses real-life Indian public transit pain points',
        ],
      },
      {
        id: 'trend-uc-4',
        trendNumber: 4,
        title: 'Minimalist Unisex Aesthetic',
        confidence: 74,
        responsesCount: 1120,
        bullets: [
          'Understated matte black, charcoal, and beige colorways',
          'Professional enough for office, casual enough for campus',
          'Zero loud logos or garish branding elements',
        ],
      },
    ],
    aiInsightQuote:
      'Commuters want slim, structured bags that protect tech with dedicated insulated bottle sleeves and water-resistant bases while looking sophisticated for university and office use.',
    analytics: {
      weeklyDemand: [
        { week: 'Week 1', validations: 190, heightPct: '26%' },
        { week: 'Week 2', validations: 290, heightPct: '39%' },
        { week: 'Week 3', validations: 410, heightPct: '54%' },
        { week: 'Week 4', validations: 550, heightPct: '70%' },
        { week: 'Week 5', validations: 680, heightPct: '83%' },
        { week: 'Week 6', validations: 830, heightPct: '94%' },
      ],
      demographics: [
        { group: '18–24 years', pct: 40, count: 400, color: '#4f46e5' },
        { group: '25–30 years', pct: 42, count: 420, color: '#f59e0b' },
        { group: '31–40 years', pct: 14, count: 140, color: '#0d9488' },
        { group: '41+ years', pct: 4, count: 40, color: '#6366f1' },
      ],
      priceSensitivity: [
        { price: '₹799', acceptancePct: 84 },
        { price: '₹999', acceptancePct: 72 },
        { price: '₹1,199', acceptancePct: 53 },
        { price: '₹1,399', acceptancePct: 35 },
        { price: '₹1,599+', acceptancePct: 18 },
      ],
      productAreaDemand: [
        { area: 'Everyday Commute Totes', count: 116, pct: 100 },
        { area: 'Tech Backpacks', count: 88, pct: 76 },
        { area: 'Sling Bags', count: 58, pct: 50 },
        { area: 'Laptop Sleeves', count: 44, pct: 38 },
      ],
    },
  },
];

export const INITIAL_DRAFT_IDEAS: Idea[] = [
  {
    id: 'draft-1',
    company: 'Nuvie',
    targetStartupName: 'Nuvie',
    category: 'Food & Beverage',
    cat: 'Food & Beverage',
    title: 'Masala Peanut Protein Bite',
    tagline: 'Spicy roasted peanut bite with 12g protein and Indian chaat masala flavor profile.',
    desc: 'Spicy roasted peanut bite with 12g protein and Indian chaat masala flavor profile. Single bite-size format for office desk snacking.',
    problemStatement: 'Indian working professionals crave savory snacks at 4 PM (like bhujia or samosa) and find sweet protein bars unappealing.',
    proposedSolution: 'Formulate savory bite-size protein crisps tossed in authentic cumin and chaat masala with cold-pressed peanut oil.',
    targetAudience: 'Office commuters, 22–35 working professionals',
    keyBenefits: ['Savory Indian masala taste', '12g clean protein', 'Zero sweet aftertaste'],
    tags: ['Masala', 'SavorySnack', 'Protein', 'OfficeSnack'],
    author: { id: 'usr-innovator', name: 'Community Innovator', username: 'innovator', avatarUrl: '🦊', reputationScore: 842, badge: 'Innovator' },
    score: 0,
    buy: 0,
    opp: 0,
    status: 'Draft',
    commentsCount: 0,
    upvotesCount: 0,
    viewsCount: 0,
    price: '₹35–₹45 per pack',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    validation: {
      viewsCount: 0,
      supportersCount: 0,
      wouldTryPercentage: 0,
      topConsumerPreferences: ['Savory profile preference', 'Sub-₹40 packaging expectation'],
      targetPriceRange: '₹35–₹45',
      engagementRate: '0%',
      categoryInterestScore: 0,
    },
  },
  {
    id: 'draft-2',
    company: 'Giftly',
    targetStartupName: 'Giftly',
    category: 'Gifting',
    cat: 'Gifting',
    title: 'Minimal Gift Hamper Builder',
    tagline: 'Modular 3-item recycled kraft cardboard gift box with personalized message cassette.',
    desc: 'Modular 3-item recycled kraft cardboard gift box with personalized message cassette under ₹499.',
    problemStatement: 'Sending small celebratory gifts (like college birthdays or team milestones) currently requires buying oversized ₹2,000 hampers.',
    proposedSolution: 'Allow custom curation of 3 artisan micro-items in a pocket-sized kraft box with seeded paper message.',
    targetAudience: 'College students and young teams',
    keyBenefits: ['Affordable gifting under ₹500', '100% recyclable kraft packaging', 'Fast custom message cassette'],
    tags: ['Gifting', 'EcoCraft', 'MiniHamper', 'Personalized'],
    author: { id: 'usr-innovator', name: 'Community Innovator', username: 'innovator', avatarUrl: '🦊', reputationScore: 842, badge: 'Innovator' },
    score: 0,
    buy: 0,
    opp: 0,
    status: 'Draft',
    commentsCount: 0,
    upvotesCount: 0,
    viewsCount: 0,
    price: '₹399–₹499',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
    validation: {
      viewsCount: 0,
      supportersCount: 0,
      wouldTryPercentage: 0,
      topConsumerPreferences: ['Recyclable packaging', 'Sub-₹500 pricing'],
      targetPriceRange: '₹399–₹499',
      engagementRate: '0%',
      categoryInterestScore: 0,
    },
  },
];
